name: publish

on:
  release:
    types: [published, created, edited]

jobs:
  # Install dependencies.
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn --frozen-lockfile

  # Publish to NPM if version defined in package.json is not published.
  publish:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      # Because of prepublishOnly script, it will be cleaned and built before published.
      - run: npx can-npm-publish --verbose && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
