name: publish

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  # Publish to NPM if version defined in package.json is not published.
  publish:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      # Install dependencies.
      - run: yarn --frozen-lockfile
      # Because of prepublishOnly script, it will be cleaned and built before published.
      - run: npx can-npm-publish --verbose && npm publish
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
